services:
  project-img:
    container_name: project-img-container
    image: pom-java-project
    build: .
    command: mvn clean test -DexecutionMode=grid -DgridUrl=http://selenium-hub:4444/wd/hub
    depends_on:
      selenium-hub:
        condition: service_healthy
      session_browser_one:
        condition: service_healthy
      session_browser_two:
        condition: service_healthy
    networks:
      - selenium_net

  selenium-hub:
    image: selenium/hub:4.19.1
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/wd/hub/status"]
      interval: 5s
      timeout: 10s
      retries: 5

  session_browser_one:
    image: selenium/node-chrome:4.19.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
    ports:
      - "6901:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/wd/hub/status"]
      interval: 5s
      timeout: 10s
      retries: 5

  session_browser_two:
    image: selenium/node-chrome:4.19.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
    ports:
      - "6902:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/wd/hub/status"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  selenium_net:
    driver: bridge